version: '3.8'

services:
  trading-bot:
    build: .
    container_name: trading-bot-minimal
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config:ro
      - ./data:/app/data
    environment:
      - EXCHANGE_API_KEY=${EXCHANGE_API_KEY}
      - EXCHANGE_SECRET_KEY=${EXCHANGE_SECRET_KEY}
      - ENVIRONMENT=production
      - DEBUG=false
    mem_limit: 400m
    cpus: 0.8
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge